servers:
  web:
    hosts:
      - 72.61.46.31
    proxy: false
    options:
      publish:
        - "127.0.0.1:8081:8080"

env:
  clear:
    HLDR_ADDR: 0.0.0.0:8080
    HLDR_CONTENT_DIR: /app/content
    HLDR_DATABASE: /var/lib/hldr/hldr.db
    HLDR_ORIGIN: https://hldr.apollo.hvpaiva.dev
    HLDR_LOG: info

volumes:
  - /var/lib/hldr-staging:/var/lib/hldr
